flasky-dev/app/views/auth.py
from flask import Blueprint
from flask import jsonify
from flask import render_template
from flask import request , url_for ,flash , redirect
from flask_login import login_required , login_user , logout_user
from flask_login import current_user
from forms import LoginForm , NameForm , ChangePasswordForm , ResetPasswordRequestForm ,ResetPasswordForm
from ..models import User , Role
from .. import db
from ..email import send_mail

auth = Blueprint('auth' , __name__)

@auth.before_app_request
def before_app_request():
	if current_user.is_authenticated:
		current_user.ping()
		if not current_user.confirmed:
			if request.endpoint is not None and request.endpoint[:5] != 'auth.' and request.endpoint != 'static':
				return redirect(url_for('auth.unconfirmed'))		

@auth.route('/confirm/<token>')
@login_required
def confirm(token):
	if current_user.confirmed:
		return redirect(url_for('main.welcome'))
	if current_user.confirm(token):
		flash('You have confirmed your account. Thanks!')
	else:
		flash('Your confirmation link is invalid!')

	return redirect(url_for('main.welcome'))

@auth.route('/unconfirmed')
def unconfirmed():
	if current_user.is_anonymous or current_user.confirmed:
		return redirect(url_for('main.welcome'))
	flash('Your account is not confirmed!')
	return render_template('auth/unconfirmed.html')

@auth.route('/reconfirm')
@login_required
def reconfirm():
	token = current_user.generate_confirmation_token()
	# print url_for('auth.confirm' , token = token , _external = True)
	send_mail(current_user.email , 'Confirm Your Account',
			'auth/email/confirm' , user=current_user , token=token)
	flash('A new confirmation email has been sent to you by email.')
	return redirect(url_for('main.welcome'))

@auth.route('/login' , methods=['GET' , 'POST'])
def login():
	login_form = LoginForm()
	if login_form.validate_on_submit():
		user = User.query.filter_by(email = login_form.email.data).first()
		if user is not None and user.verify_password(login_form.password.data):
			login_user(user , login_form.remember_me.data)
			return redirect(request.args.get('next') or url_for('main.welcome'))
		flash('Invalid username or password.')
	return render_template('auth/login.html' , form = login_form)

@auth.route('/logout' , methods=['GET'])
def logout():
	logout_user()
	flash('You have been logged out.')
	return redirect(url_for('main.welcome'))

@auth.route('/register' , methods=['GET' , 'POST'])
def register():
	form = NameForm()
	if form.validate_on_submit():
		user = User(username = form.name.data,
				password = form.pswd.data,
				email = form.email.data,
				location = form.location.data,
				info = form.info.data)
		db.session.add(user)
		db.session.commit()
		token = user.generate_confirmation_token()
		# print url_for('auth.confirm' , token=token , _external=True)
		send_mail(user.email , 'Confirm Your Account',
			'auth/email/confirm' , user=user , token=token)
		flash('A confirmation email has been sent to you by email.')
		return redirect(url_for('auth.login'))
			 
		# print type(form.name.data) , type(form.email.data) , type(form.role.data) ,type(form.info.data)
	return  render_template('auth/register.html', form = form)

	# if request.method == 'GET':
	# 	return  render_template('index.html' , user_agent= user_agent , form = NameForm() , current_time=datetime.utcnow())
	# elif request.method == 'POST':
	# 	form = request.form
	# 	return render_template('summary.html',
	# 		name = form['name'],
	# 		email = form['email'],
	# 		info = form['info'])
@auth.route('/change-password' , methods = ['GET' , 'POST'])
@login_required
def change_password():
	form = ChangePasswordForm()
	if form.validate_on_submit():
		if current_user.verify_password(form.oldpass.data):
			current_user.password = form.newpass.data
			db.session.add(current_user)
			flash('Your password has been updated!')
			return redirect(url_for('main.welcome'))
		else:
			flash('Invalid password!')
	return render_template('auth/change-password.html' , form = form)

@auth.route('/reset' , methods = ['GET' , 'POST'])
def reset_password_request():
	if not current_user.is_anonymous:
		redirect(url_for('main.welcome'))
	form = ResetPasswordRequestForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email = form.email.data).first()
		if user:
			token = user.generate_reset_token()
			send_mail(user.email , 'Reset Your Password',
				'auth/email/reset_password' , user=user , token=token)
			# print url_for('auth.reset_password' , token = token , _external=True)
			flash('An email with instructions to reset your password has been sent to you.')
		return redirect(url_for('auth.login'))

	return render_template('auth/reset-password.html',form = form)

@auth.route('/reset/<token>' , methods = ['GET' , 'POST'])
def reset_password(token):
	if not current_user.is_anonymous:
		redirect(url_for('main.welcome'))

	form = ResetPasswordForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email = form.email.data).first()
		if user is None:
			return redirect(url_for('main.welcome'))
		if user.reset_password(token , form.password.data):
			flash('Your password has been updated.')
			return redirect(url_for('auth.login'))
		else:
			return redirect(url_for('main.welcome'))

	return render_template('auth/reset-password.html' , form = form)

flasky-dev/app/views/main.py
import time
from datetime import datetime
from flask import render_template,request,flash,redirect , url_for,current_app,make_response,abort
from .forms import NameForm , RoleForm , EditProfileForm , EditProfileAdminForm , PostForm,CommentForm
from .. import db 
from ..models import User , Role , Permission , Post , Comment
from .. import login_manager
from flask_login import login_required , current_user
from ..decorators import permission_required , admin_required


current_milli_time = lambda : int(round(time.time() * 1000))

def get_current_ts():
	now = datetime.now()
	ts = time.mktime(now.timetuple())
	return ts

from flask import Blueprint

main = Blueprint('main' , __name__)
@main.app_context_processor
def inject_permissions():
	return dict(Permission=Permission)

@main.route('/all-posts')
@login_required
def show_all():
	resp = make_response(redirect(url_for('main.welcome')))
	resp.set_cookie('show_followed' , '' , max_age=60*60)
	return resp

@main.route('/followed-posts')
@login_required
def show_followed():
	resp = make_response(redirect(url_for('main.welcome')))
	resp.set_cookie('show_followed','1' , max_age=60*60)
	return resp

@main.route('/' , methods =['GET' , 'POST'])
def welcome():
	user_agent = request.headers.get('User-Agent')
	users = None
	if current_user.is_authenticated and current_user.is_administrator():
		users = User.query.all()

	form = PostForm()
	if current_user.can(Permission.WRITE_ARTICLES) and form.validate_on_submit():
		post = Post(body = form.body.data , author=current_user._get_current_object())
		db.session.add(post)
		return redirect(url_for('main.welcome'))
	show_followed = False
	if current_user.is_authenticated:
		show_followed = bool(request.cookies.get('show_followed' , ''))

	if show_followed:
		query = current_user.followed_posts
	else:
		query = Post.query

	page = request.args.get('page', 1 ,type=int)
	pagination = query.order_by(Post.timestamp.desc()).paginate(page ,
		per_page=current_app.config['FLASKY_DEV_POSTS_PER_PAGE'] , 
		error_out=False)
	posts = pagination.items
	return render_template('welcome.html' , 
		user_agent = user_agent , 
		users = users , 
		current_time = datetime.utcnow(),
		post_form = form , 
		posts = posts ,
		pagination = pagination)

@main.route('/user/<name>')
def user(name):
	user = User.query.filter_by(username = name).first()
	if user is None:
		abort(404)
	page = request.args.get('page', 1 ,type=int)
	pagination = user.posts.order_by(Post.timestamp.desc()).paginate(page ,
		per_page=current_app.config['FLASKY_DEV_POSTS_PER_PAGE'] , 
		error_out=False)
	posts = pagination.items

	return render_template('user.html',user=user , posts = posts , pagination=pagination)

@main.route('/post/<int:id>' , methods=['GET' , 'POST'])
def post(id):
	post = Post.query.get_or_404(id)
	form = CommentForm()
	if form.validate_on_submit():
		comment = Comment(body = form.body.data , post = post , author=current_user._get_current_object())
		db.session.add(comment)
		flash('Your comment has been published.')
		return redirect(url_for('main.post' , id = post.id , page=-1))
	page = request.args.get('page',1,type=int)
	if page == -1 or page == 0:
		page = (post.comments.count() -1)/(current_app.config['FLASKY_DEV_COMMENTS_PER_PAGE']) + 1
		print post.comments.count(),page
		if page == -1 or page == 0:
			page = 1

	pagination = post.comments.order_by(Comment.timestamp.asc()).paginate(page,
		per_page = current_app.config['FLASKY_DEV_COMMENTS_PER_PAGE'],
		error_out = False)

	comments = pagination.items

	return render_template('post.html' , comments = comments , form=form , posts = [post] , pagination = pagination)

@main.route('/moderate')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate():
	page = request.args.get('page' , 1 , type=int)
	pagination = Comment.query.order_by(Comment.timestamp.desc()).paginate(page , 
		per_page=current_app.config['FLASKY_DEV_COMMENTS_PER_PAGE'],
		error_out=False)
	comments = pagination.items
	return render_template('moderate.html' , comments=comments,pagination=pagination,page = page)

@main.route('/moderate/enable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_enable(id):
	comment = Comment.query.get_or_404(id)
	comment.disabled = False
	db.session.add(comment)
	return redirect(url_for('main.moderate' , page=request.args.get('page',1,type=int)))

@main.route('/moderate/disable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_disable(id):
	comment = Comment.query.get_or_404(id)
	comment.disabled = True
	db.session.add(comment)
	return redirect(url_for('main.moderate' , page=request.args.get('page',1,type=int)))

@main.route('/editpost/<int:id>' , methods=['GET','POST'])
def editpost(id):
	post = Post.query.get_or_404(id)
	if current_user != post.author and not current_user.is_administrator():
		abort(403)

	form = PostForm()
	if form.validate_on_submit():
		post.body = form.body.data
		db.session.add(post)
		flash('The post has been updated.')
		return redirect(url_for('main.post' , id = post.id))
	form.body.data = post.body
	return render_template('edit_post.html' , form = form)

@main.route('/follow/<name>' , methods=['GET'])
@login_required
@permission_required(Permission.FOLLOW)
def follow(name):
	user = User.query.filter_by(username = name).first()
	if user is None:
		flash('Invalid user.')
		return redirect(url_for('main.welcome'))

	if current_user.is_following(user):
		flash('You are already following %s.' %name)
		return redirect(url_for('main.user' , name = name))

	current_user.follow(user)
	flash('You are following %s.' %name)
	return redirect(url_for('main.user' , name = name))

@main.route('/unfollow/<name>' , methods=['GET'])
@login_required
def unfollow(name):
	user = User.query.filter_by(username = name).first()
	if user is None:
		flash('Invalid user.')
		return redirect(url_for('main.welcome'))

	if not current_user.is_following(user):
		flash('You haven`t followed %s.' %name)
		return redirect(url_for('main.user' , name = name))

	current_user.unfollow(user)
	flash('Unfollowing %s.' %name)
	return redirect(url_for('main.user') , name = name)

@main.route('/followers/<name>' , methods=['GET'])
@login_required
def followers(name):
	user = User.query.filter_by(username = name).first()
	if user is None:
		flash('Invalid user.')
		return redirect(url_for('main.welcome'))
	page = request.args.get('page' , 1 ,type=int)
	pagination = user.followers.paginate(page , 
		per_page=current_app.config['FLASKY_DEV_POSTS_PER_PAGE'] , 
		error_out = False)
	followers = [{'user':item.follower , 'timestamp':item.timestamp}
				for item in pagination.items]

	return render_template('followers.html' , user=user , title="Followers of",
		endpoint='main.followers',pagination=pagination , followers=followers)
@main.route('/followed/<name>' , methods=['GET'])
def followed(name):
	user = User.query.filter_by(username = name).first()
	if user is None:
		flash('Invalid user.')
		return redirect(url_for('main.welcome'))		
	page = request.args.get('page' , 1 ,type=int)
	pagination = user.followed.paginate(page , 
		per_page=current_app.config['FLASKY_DEV_POSTS_PER_PAGE'] , 
		error_out = False)

	follows = [{'user':item.followed , 'timestamp':item.timestamp}
				for item in pagination.items]

	return render_template('followers.html' , user=user , title = "Followed by",
		endpoint='main.followed' , pagination=pagination , followers = follows)

@main.route('/edit-profile' , methods = ['GET' , 'POST'])
@login_required
def edit_profile():
	form = EditProfileForm()
	if form.validate_on_submit():
		current_user.location = form.location.data
		current_user.info = form.info.data
		db.session.add(current_user)
		flash('Your profile has been updated.')
		return redirect(url_for('main.user' , name = current_user.username))

	form.location.data = current_user.location
	form.info.data = current_user.info
	return render_template('edit_profile.html' , form=form)

@login_required
@admin_required
@main.route('/edit-profile/<int:id>' , methods=['GET' , 'POST'])
def edit_profile_admin(id):
	user = User.query.get_or_404(id)
	form = EditProfileAdminForm( user = user)
	if form.validate_on_submit():
		user.email = form.email.data
		user.username = form.name.data
		user.confirmed = form.confirmed.data
		user.user_role = Role.query.get(form.role.data)
		user.location = form.location.data
		user.info = form.info.data
		db.session.add(user)
		flash('The profile has been updated.')
		return redirect(url_for('main.user',name = user.username))

	form.email.data = user.email
	form.name.data = user.username
	form.confirmed.data = user.confirmed
	form.role.data = user.role_id
	form.location.data = user.location
	form.info.data = user.info
	return render_template('edit_profile.html' , form=form)


# @main.route('/user/<name>')
# def user(name):
# 	return render_template('user.html' , name = name)
@login_required
@admin_required
@main.route('/admin',methods = ['GET'])
def admin_role():
	return redirect(url_for('main.welcome'))
	# form = RoleForm()
	# if form.validate_on_submit():
	# 	role = Role.query.filter(Role.name == form.role.data).first()
	# 	users = []
	# 	if role is None:
	# 		users = None
	# 	for user in role.users:
	# 		users.append(user.username)

	# 	return render_template('role.html',users = users)

	# return render_template('role.html' , form = RoleForm())

flasky-dev/app/templates/_comments.html
<ul class="comments">
	{% for comment in comments%}
	<li class="comment">
		<div class="comment-thumbnail">
			<a href="{{ url_for('main.user' , name=comment.author.username) }}">
				<img class="img-rounded profile-thumbnail" src="{{ comment.author.gravatar(size=40)}}">
			</a>
		</div>
		<div class="comment-content">
			<div class="comment-date">{{ moment(comment.timestamp).fromNow() }}</div>
			<div class="comment-author">{{comment.author.username}}</div>
			<div class="comment-body">
			{% if comment.disabled %}
			<p><i>This comment has been disabled by a moderator.</i></p>
			{% endif %}
			{% if moderate or not comment.disabled %}
				{% if comment.body_html %}
					{{ comment.body_html | safe}}
				{% else %}
					{{ comment.body }}
				{% endif %}
			{% endif %}
			</div>
		</div>
		{% if moderate %}
			<br>
			{% if comment.disabled %}
			<a class="btn btn-default btn-xs" href="{{ url_for('main.moderate_enable' , id=comment.id , page=page)}}">Enable</a>
			{% else %}
			<a class="btn btn-danger btn-xs" href="{{ url_for('main.moderate_disable',id=comment.id,page=page)}}">Disable</a>
			{% endif %}
		{% endif %}
	</li>
	{% endfor %}
</ul>

flasky-dev/app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
	<li{% if not pagination.has_prev %} class="disabled" {% endif %}>
		<a href="{% if pagination.has_prev %}{{url_for(endpoint , page=pagination.page - 1,**kwargs)}}{% else %}#{% endif %}">&laquo;</a>
	</li>
	{% for p in pagination.iter_pages() %}
		{% if p %}
			{% if p == pagination.page %}
			<li class="active">
				<a href="{{url_for(endpoint, page=p,**kwargs)}}">{{p}}</a>
			</li>
			{% else %}
			<li>
				<a href="{{url_for(endpoint, page=p,**kwargs)}}">{{p}}</a>
			</li>
			{% endif %}
		{% else %}
		<li class="disabled"><a href="#">&hellip;</a></li>
		{% endif %}
	{% endfor %}
	<li{% if not pagination.has_next %} class="disabled"{% endif %}>
	<a href="{% if pagination.has_next %}{{ url_for(endpoint , page=pagination.page+1,**kwargs)}}{% else %}#{% endif %}">&raquo;</a>	
	</li>
</ul>
{% endmacro %}

flasky-dev/app/templates/_posts.html
<ul class="posts">
{% for post in posts %}
	<li class="post">
		<div class="profile-thumbnail">
			<a href="{{ url_for('main.user' , name=post.author.username) }}">
				<img class="img-rounded profile-thumbnail" src="{{post.author.gravatar(size=40) }}">
			</a>
		</div>
		<div class="post-content">
			<div class="post-data">{{ moment(post.timestamp).fromNow()}}</div>
			<div class="post-author">
				<a href="{{ url_for('main.user' , name=post.author.username)}}">
							{{post.author.username}}
				</a>
			</div>
			<div class="post-body">
			{% if post.body_html %}
				{{ post.body_html | safe }}
			{% else %}
				{{ post.body }}
			{% endif %}
			</div>
			<div class="post-footer">
				{% if current_user == post.author%}
				<a href="{{ url_for('main.editpost' , id = post.id) }}">
					<span class="label label-primary">Edit</span>
				</a>
				{% elif current_user.is_administrator() %}
				<a href="{{ url_for('main.editpost' , id = post.id) }}">
					<span class="label label-danger">Edit[Admin]</span>
				</a>
				{% endif %}
				<a href="{{ url_for('main.post' , id = post.id) }}">
					<span class="label label-default">Permalink</span>
				</a>
				<a href="{{ url_for('main.post' , id=post.id) }}#comments">
					<span class="label label-primary">
						{{ post.comments.count() }} Comments
					</span>
				</a>
			</div>
		</div>
	</li>
{% endfor %}
</ul>

flasky-dev/app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block head %}
{{ super() }}
<link rel="icon" type="image/x-icon" href="{{url_for('static' , filename = 'fav.ico')}}">
<link rel="stylesheet" type="text/css" href="{{ url_for('static' , filename='style.css') }}">
{% endblock %}
{% block title %}Flasky-dev{% endblock %}
{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
	<div class="container">
		<div class="navbar-header">
<!-- 		<button type="button" class="navbar-toggle" data-toggle="collapse" 
		data-target=".navbar-collapse">
		<span class="sr-only">Toggle navigation</span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		</button> -->
		<a class="navbar-brand" href="/">Flasky-dev</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li><a href="/">Home</a></li>
				<!-- <li><a href="/role">roles</a></li> -->
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% if current_user.is_authenticated %}
				<img class="img-rounded profile-thumbnail" src="{{ current_user.gravatar(size=32)}}">
				<li><a href="{{ url_for('main.user',name = current_user.username )}}">Profile</a></li>
				<li><a href="{{ url_for('auth.logout') }}">Sign Out</a></li>
				{% else %}
				<li><a href="{{ url_for('auth.login') }}">Sign In</a></li>
				{% endif %}
				{% if current_user.can(Permission.MODERATE_COMMENTS) %}
				<li><a href="{{url_for('main.moderate')}}">Moderate Comments</a></li>
				{% endif %}
			</ul>
		</div>
	</div>
</div>
{% endblock %}

{% block content %}
<div class="container">
	{% for message in get_flashed_messages() %}
	<div class="alert alert-warning">
		<button type="button" class="close" data-dismiss="alert">close</button>
		{{ message }}
	</div>
	{% endfor %}
	{% block page_content %}
	{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

flasky-dev/app/templates/edit_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Flasky-dev Edit Post {% endblock %}

{% block page_content %}
<div class="page-header">
	<h1>Edit Post</h1>
</div>
<div>
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

flasky-dev/app/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %} Edit Profile {% endblock %}

{% block page_content %}
<div class="container">
	<div class="page-header">
		<h1>Edit Profile</h1>
	</div>
	{{ wtf.quick_form(form) }}
</div>
{% endblock %}

flasky-dev/app/templates/followers.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}

{% block title %}{{title}} {{user.username}}{% endblock %}

{%block page_content%}
<div class="page-header">
	<h1>{{title}} {{user.username}}</h1>
</div>

<table class="table table-hover followers">
	<thead><tr><th>User</th><th>Since</th></tr></thead>
	{% for follow in followers %}
	<tr>
		<td>
			<a href="{{ url_for('main.user' , name=follow.user.username )}}">
				<img class="img-rounded" src="{{ follow.user.gravatar(size=32)}}">
				{{ follow.user.username }}
			</a>
		</td>
		<td>{{ moment(follow.timestamp).format('L') }}</td>
	</tr>
	{% endfor %}
</table>
<div class="pagination">
	{{ macros.pagination_widget(pagination , endpoint , name = user.username)}}
</div>
{% endblock %}

flasky-dev/app/templates/moderate.html
{% extends 'base.html' %}
{% import '_macros.html' as macros %}

{% block title %}Flasky-dev Comments Moderate{% endblock %}

{% block page_content %}
<div class="page-header">
	<h1>Comment Moderation</h1>
</div>
{% set moderate = True %}
{% include '_comments.html' %}
{% if pagination %}
<div class="pagination">
	{{ macros.pagination_widget(pagination , 'main.moderate') }}
</div>
{% endif %}
{% endblock %}

flasky-dev/app/templates/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros%}

{% block title %} Flasky-dev Post {% endblock %}

{% block page_content %}
{% include '_posts.html' %}
<h4 id="comments">Comments</h4>
{% if current_user.can(Permission.COMMENT) %}
<div class="comment-form">
	{{ wtf.quick_form(form) }}
</div>
{% endif %}
{% include '_comments.html' %}
{% if pagination %}
<div class="pagination">
	{{ macros.pagination_widget(pagination , 'main.post' , fragment='#comments' , id = posts[0].id) }}	
</div>

{% endif %}
{% endblock %}

flasky-dev/app/templates/role.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wft %}
{% block title %}Roles!{% endblock %}

{% block page_content %}
<div class="container">
	<div class="page-header">
		<h1>Welcome to flasky web server!</h1>
	</div>
	{% if form %}
	{{ wft.quick_form(form) }}
	{% endif %}
	<div>
		<ul>
		{% for user in users%}
		<li>{{user}}</li>
		{% endfor %}
		</ul>
	</div>
	
</div>

{% endblock %}

flasky-dev/app/templates/user.html
{% extends "base.html" %}
{% import "_macros.html" as macros %}
{% block title %}User Page{% endblock %}

{% block page_content %}
<div class="container">
	<div class="page-header">
		<img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=256)}}">
		<h1>hello , {{user.username}}!</h1>
		
		{% if user.location %}
		<p>From <a href="http://maps.google.com/?q={{ user.location }}">{{user.location}}</a></p>
		{% endif %}

		{% if user.info %}
			<p> {{user.info}} </p>
		{% endif %}
		<p> Member since {{ moment(user.member_since).format('L') }}.
		Last seen {{ moment(user.last_seen).fromNow(refresh=True) }}.</p>

		{% if user.posts %}
		<p> {{user.posts.count()}} blog posts</p>
		{% endif %}

		{% if current_user.can(Permission.FOLLOW) and current_user != user%}
			{% if not current_user.is_following(user) %}
				<a href="{{ url_for('main.follow' , name = user.username)}}" 
					class="btn btn-primary">Follow</a>
			{% else %}
				<a href="{{ url_for('main.unfollow' , name = user.username)}}"
					class="btn btn-default">Unfollow</a>
			{% endif %}
		{% endif %}
		<a href="{{ url_for('main.followers' , name=user.username) }}">
			Followers : <span class="badge">{{ user.followers.count() }}</span>
		</a>
		<a href="{{ url_for('main.followed' , name=user.username) }}">
			Following : <span class="badge">{{ user.followed.count() }}</span>
		</a>

		{% if current_user.is_authenticated and user != current_user and user.is_following(current_user)%}
		| <span class="label label-default">Follows you</span>
		{% endif %}
	</div>	
	{% if current_user.is_administrator() %}
	<p>EmailTo:<a href="mailto:{{ user.email }}">{{user.email}}</a></p>
	{% endif %}

	<ul>
		{% if user == current_user%}
		<li><a class = "btn btn-default" href="{{ url_for('main.edit_profile')}}">Edit Profile</a></li><li><a class = "btn btn-default" href="{{ url_for('auth.change_password')}}">Change Password</a></li>
		{% endif %}
		{% if current_user.is_administrator() %}
		<li><a class = "btn btn-danger" href="{{ url_for('main.edit_profile_admin' , id = user.id ) }}">Edit Profile [Admin]</a></li>
		{% endif %}
	</ul>

	<h3>Posts by {{user.username}}</h3>
	{% include '_posts.html' %}
	<div class="pagination">
		{{ macros.pagination_widget(pagination , 'main.user' , name=user.username)}}
	</div>
</div>
{% endblock %}

flasky-dev/app/templates/welcome.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}
{% block title %}Welcome!{% endblock %}

{% block page_content %}

	<div class="page-header">
		<h1>Welcome to flasky web server!</h1>
	</div>
	{% if current_user.is_authenticated %}
		<h3>Hello ! {{current_user.username}}</h3>
<!-- 		{% if users %}
		<div>
				<ul>
					{% for user in users %}
					<li><a href="{{ url_for('main.edit_profile_admin' , id = user.id) }}">{{user.username}}({{user.email}})</a></li>
					{% endfor %}
				</ul>
		</div>
		{% endif %} -->
		<div>
				{% if current_user.can(Permission.WRITE_ARTICLES) %}
				{{ wtf.quick_form(post_form)}}
				{% endif %}
		</div>
		<div class="post-tabs">
			<ul class="nav nav-tabs">
				<li{% if not show_followed %} class="active" {% endif %}><a href="{{url_for('main.show_all')}}">All</a></li>
				{% if current_user.is_authenticated %}
				<li{% if show_followed %} class="active" {% endif %}><a href="{{ url_for('main.show_followed')}}"></a>Followers</li>	
				{% endif %}
			</ul>
			{% include '_posts.html' %}
		</div>

		<div class="pagination">
			{{ macros.pagination_widget(pagination , 'main.welcome')}}
		</div>
	{% else %}
		<ul>
			<li><a href="{{ url_for('auth.register') }}">Register</a></li>
			<li><a href="{{ url_for('auth.login') }}">Login</a></li>
		</ul>
	{% endif %}
	<p>Your browser is {{user_agent}}</p>
	<p>{{moment(current_time).format('LLLL')}}.</p><br>
	<p>That was {{moment(current_time).fromNow(refresh=True)}}</p>

{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}